spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetpulse
    username: ${DB_USER:fleetpulse}
    password: ${DB_PASSWORD:fleetpulse}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/seed
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:fleetpulse}
    password: ${RABBITMQ_PASSWORD:fleetpulse}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/fleetpulse}
keycloak:
  admin:
    server-url: http://localhost:8081
    realm: fleetpulse
    client-id: fleet-api
    client-secret: ${KEYCLOAK_CLIENT_SECRET:VNLGjDK3YyWJnBh1YZllpDHNlpOL8QGb}
management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: ${SERVER_PORT:8090}
