-- ============================================================
-- V10__seed_sample_data.sql
-- Development/demo seed data — all UUIDs are auto-generated by
-- PostgreSQL's gen_random_uuid() default. Relations are chained
-- via CTEs (RETURNING) within a single INSERT, or via natural-key
-- joins (license_plate, email) across separate statements once
-- prior rows are visible within the same migration transaction.
-- ============================================================

-- ---------------------------------
-- FLEETS (3)
-- ---------------------------------
INSERT INTO fleet (name, created_at)
SELECT name, created_at
FROM (VALUES
    ('Flotte Nord',              NOW() - INTERVAL '120 days'),
    ('Flotte Sud',                NOW() - INTERVAL '90 days'),
    ('Flotte Logistique Paris',   NOW() - INTERVAL '60 days')
) AS f(name, created_at)
WHERE NOT EXISTS (
    SELECT 1 FROM fleet WHERE fleet.name = f.name
);

-- ---------------------------------
-- APP USERS (7)
-- ---------------------------------
INSERT INTO app_user (keycloak_id, email, full_name, role, status, created_at)
VALUES
    ('kc-admin-0001',   'admin@fleetpulse.local',   'Sophie Admin',  'ADMIN',         'ENABLED',  NOW() - INTERVAL '120 days'),
    ('kc-manager-0001', 'j.martin@fleetpulse.local','Julie Martin',  'FLEET_MANAGER', 'ENABLED',  NOW() - INTERVAL '100 days'),
    ('kc-manager-0002', 'p.durand@fleetpulse.local','Pierre Durand', 'FLEET_MANAGER', 'ENABLED',  NOW() - INTERVAL '80 days'),
    ('kc-tech-0001',    'k.benali@fleetpulse.local','Karim Benali',  'TECHNICIAN',    'ENABLED',  NOW() - INTERVAL '70 days'),
    ('kc-tech-0002',    'l.moreau@fleetpulse.local','Léa Moreau',    'TECHNICIAN',    'ENABLED',  NOW() - INTERVAL '65 days'),
    ('kc-tech-0003',    's.haddad@fleetpulse.local','Sami Haddad',   'TECHNICIAN',    'ENABLED',  NOW() - INTERVAL '50 days'),
    ('kc-tech-0004',    'n.leroy@fleetpulse.local', 'Nadia Leroy',   'TECHNICIAN',    'DISABLED', NOW() - INTERVAL '110 days')
ON CONFLICT (keycloak_id) DO NOTHING;

-- ---------------------------------
-- VEHICLES (18) — fleet_id resolved via a join on fleet.name,
-- since fleet rows above already have their generated ids visible
-- within this migration's transaction.
-- ---------------------------------
INSERT INTO vehicle (fleet_id, license_plate, brand, model, vehicle_type, status, registered_at)
SELECT f.id, v.license_plate, v.brand, v.model, v.vehicle_type, v.status, v.registered_at
FROM (VALUES
          ('Flotte Nord',              'AA-001-AA', 'Renault',  'Master',   'VAN',   'ACTIVE',         NOW() - INTERVAL '110 days'),
          ('Flotte Nord',              'AA-002-AA', 'Renault',  'Master',   'VAN',   'ACTIVE',         NOW() - INTERVAL '108 days'),
          ('Flotte Nord',              'AA-003-AA', 'Mercedes', 'Sprinter', 'VAN',   'MAINTENANCE',    NOW() - INTERVAL '105 days'),
          ('Flotte Nord',              'AA-004-AA', 'Volvo',    'FH16',     'TRUCK', 'ACTIVE',         NOW() - INTERVAL '100 days'),
          ('Flotte Nord',              'AA-005-AA', 'Volvo',    'FH16',     'TRUCK', 'ACTIVE',         NOW() - INTERVAL '98 days'),
          ('Flotte Nord',              'AA-006-AA', 'Peugeot',  '308',      'CAR',   'ACTIVE',         NOW() - INTERVAL '95 days'),
          ('Flotte Sud',                'BB-001-BB', 'Renault',  'Master',   'VAN',   'ACTIVE',         NOW() - INTERVAL '90 days'),
          ('Flotte Sud',                'BB-002-BB', 'Fiat',     'Ducato',   'VAN',   'ACTIVE',         NOW() - INTERVAL '88 days'),
          ('Flotte Sud',                'BB-003-BB', 'Scania',   'R450',     'TRUCK', 'ACTIVE',         NOW() - INTERVAL '85 days'),
          ('Flotte Sud',                'BB-004-BB', 'Scania',   'R450',     'TRUCK', 'DECOMMISSIONED', NOW() - INTERVAL '82 days'),
          ('Flotte Sud',                'BB-005-BB', 'Renault',  'Clio',     'CAR',   'ACTIVE',         NOW() - INTERVAL '80 days'),
          ('Flotte Sud',                'BB-006-BB', 'Peugeot',  '308',      'CAR',   'ACTIVE',         NOW() - INTERVAL '78 days'),
          ('Flotte Logistique Paris',   'CC-001-CC', 'Mercedes', 'Sprinter', 'VAN',   'ACTIVE',         NOW() - INTERVAL '55 days'),
          ('Flotte Logistique Paris',   'CC-002-CC', 'Mercedes', 'Sprinter', 'VAN',   'ACTIVE',         NOW() - INTERVAL '52 days'),
          ('Flotte Logistique Paris',   'CC-003-CC', 'MAN',      'TGX',      'TRUCK', 'ACTIVE',         NOW() - INTERVAL '50 days'),
          ('Flotte Logistique Paris',   'CC-004-CC', 'MAN',      'TGX',      'TRUCK', 'MAINTENANCE',    NOW() - INTERVAL '48 days'),
          ('Flotte Logistique Paris',   'CC-005-CC', 'Peugeot',  '208',      'CAR',   'ACTIVE',         NOW() - INTERVAL '45 days'),
          ('Flotte Logistique Paris',   'CC-006-CC', 'Citroën',  'C3',       'CAR',   'ACTIVE',         NOW() - INTERVAL '40 days')
     ) AS v(fleet_name, license_plate, brand, model, vehicle_type, status, registered_at)
         JOIN fleet f ON f.name = v.fleet_name
ON CONFLICT (license_plate) DO NOTHING;

-- ---------------------------------
-- ALERT THRESHOLDS (4)
-- ---------------------------------
INSERT INTO alert_threshold (vehicle_type, model_version, threshold_value, created_at, updated_at)
VALUES
    ('VAN',   'v1', 0.62, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
    ('TRUCK', 'v1', 0.48, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
    ('CAR',   'v1', 0.71, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
    (NULL,    'v1', 0.60, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days')
ON CONFLICT (vehicle_type, model_version) DO NOTHING;

-- ---------------------------------
-- ALERTS (8) — vehicle_id and acknowledged_by resolved via joins
-- on license_plate and email respectively.
-- ---------------------------------
INSERT INTO alert (vehicle_id, anomaly_score_value, model_version, status, triggered_at, acknowledged_at, resolved_at, acknowledged_by, created_at, updated_at)
SELECT v.id, a.score, 'v1', a.status, a.triggered_at, a.acknowledged_at, a.resolved_at, u.id, a.triggered_at, COALESCE(a.resolved_at, a.acknowledged_at, a.triggered_at)
FROM (VALUES
          ('AA-001-AA', 0.87, 'NEW',          NOW() - INTERVAL '2 hours',    NULL::TIMESTAMP,                    NULL::TIMESTAMP,                  NULL),
          ('AA-004-AA', 0.55, 'ACKNOWLEDGED', NOW() - INTERVAL '1 day',      NOW() - INTERVAL '20 hours',         NULL,                              'j.martin@fleetpulse.local'),
          ('AA-006-AA', 0.79, 'RESOLVED',     NOW() - INTERVAL '5 days',     NOW() - INTERVAL '4 days 20 hours',  NOW() - INTERVAL '3 days',         'j.martin@fleetpulse.local'),
          ('BB-003-BB', 0.51, 'NEW',          NOW() - INTERVAL '6 hours',    NULL,                                 NULL,                              NULL),
          ('BB-005-BB', 0.74, 'ACKNOWLEDGED', NOW() - INTERVAL '3 days',     NOW() - INTERVAL '2 days 12 hours',  NULL,                              'p.durand@fleetpulse.local'),
          ('CC-001-CC', 0.68, 'RESOLVED',     NOW() - INTERVAL '10 days',    NOW() - INTERVAL '9 days 18 hours',  NOW() - INTERVAL '8 days',         'j.martin@fleetpulse.local'),
          ('CC-003-CC', 0.49, 'NEW',          NOW() - INTERVAL '30 minutes', NULL,                                 NULL,                              NULL),
          ('CC-005-CC', 0.82, 'ACKNOWLEDGED', NOW() - INTERVAL '2 days',     NOW() - INTERVAL '1 day 15 hours',   NULL,                              'p.durand@fleetpulse.local')
     ) AS a(license_plate, score, status, triggered_at, acknowledged_at, resolved_at, acknowledged_by_email)
         JOIN vehicle v ON v.license_plate = a.license_plate
         LEFT JOIN app_user u ON u.email = a.acknowledged_by_email
WHERE NOT EXISTS (
    SELECT 1 FROM alert a2
    WHERE a2.vehicle_id = v.id
    AND a2.triggered_at = a.triggered_at
);

-- ---------------------------------
-- INTERVENTIONS (7) — vehicle_id, technician_id and alert_id
-- resolved via joins on license_plate, email and (vehicle_id +
-- triggered_at) respectively.
-- ---------------------------------
INSERT INTO intervention (vehicle_id, technician_id, alert_id, status, description, technician_report, opened_at, closed_at, created_at, updated_at)
SELECT v.id, tech.id, al.id, i.status, i.description, i.technician_report, i.opened_at, i.closed_at, i.opened_at, COALESCE(i.closed_at, i.opened_at)
FROM (VALUES
          ('AA-004-AA', 'k.benali@fleetpulse.local', 'AA-004-AA', NOW() - INTERVAL '1 day',    'IN_PROGRESS', 'Vibration anormale détectée sur essieu avant.', NULL::VARCHAR,
           NOW() - INTERVAL '18 hours', NULL::TIMESTAMP),
          ('AA-006-AA', 'l.moreau@fleetpulse.local', 'AA-006-AA', NOW() - INTERVAL '5 days',    'CLOSED', 'Surchauffe moteur signalée par le modèle ML.',
           'Durite de refroidissement percée. Remplacée et niveau liquide de refroidissement complété. Test routier OK.',
           NOW() - INTERVAL '4 days 18 hours', NOW() - INTERVAL '3 days'),
          ('BB-005-BB', 's.haddad@fleetpulse.local', 'BB-005-BB', NOW() - INTERVAL '3 days',    'OPEN', 'Score de risque élevé, à investiguer.', NULL,
           NOW() - INTERVAL '2 days 10 hours', NULL),
          ('CC-001-CC', 'k.benali@fleetpulse.local', 'CC-001-CC', NOW() - INTERVAL '10 days',   'CLOSED', 'Vibration anormale sur véhicule utilitaire.',
           'Plaquettes de frein usées à 90%. Remplacées côté avant gauche et droit. Purge du circuit de freinage effectuée.',
           NOW() - INTERVAL '9 days 15 hours', NOW() - INTERVAL '8 days'),
          ('AA-003-AA', NULL,                         NULL,        NULL,                          'OPEN', 'Contrôle technique préventif planifié.', NULL,
           NOW() - INTERVAL '1 day', NULL),
          ('CC-004-CC', NULL,                         NULL,        NULL,                          'OPEN', 'Révision périodique 50 000 km.', NULL,
           NOW() - INTERVAL '12 hours', NULL),
          ('BB-004-BB', 'l.moreau@fleetpulse.local', NULL,        NULL,                          'CLOSED', 'Dernier entretien avant mise hors service.',
           'Véhicule inspecté, aucune réparation nécessaire avant décommissionnement. RAS.',
           NOW() - INTERVAL '20 days', NOW() - INTERVAL '18 days')
     ) AS i(vehicle_plate, technician_email, alert_vehicle_plate, alert_triggered_at, status, description, technician_report, opened_at, closed_at)
         JOIN vehicle v ON v.license_plate = i.vehicle_plate
         LEFT JOIN app_user tech ON tech.email = i.technician_email
         LEFT JOIN alert al ON al.vehicle_id = (SELECT id FROM vehicle WHERE license_plate = i.alert_vehicle_plate)
    AND al.triggered_at = i.alert_triggered_at
WHERE NOT EXISTS (
    SELECT 1 FROM intervention i2
    WHERE i2.vehicle_id = v.id
    AND i2.opened_at = i.opened_at
);

-- ---------------------------------
-- NOTIFICATION HISTORY (8) — alert_id resolved via join on
-- (vehicle license_plate + triggered_at), matching the alerts above.
-- ---------------------------------
INSERT INTO notification_history (alert_id, sent_to, channel, status, sent_at, created_at, updated_at)
SELECT al.id, n.sent_to, n.channel, n.status, n.alert_triggered_at, n.alert_triggered_at, n.alert_triggered_at
FROM (VALUES
          ('AA-001-AA', NOW() - INTERVAL '2 hours',    'j.martin@fleetpulse.local', 'EMAIL',   'SENT'),
          ('AA-004-AA', NOW() - INTERVAL '1 day',       'j.martin@fleetpulse.local', 'EMAIL',   'SENT'),
          ('AA-006-AA', NOW() - INTERVAL '5 days',      'j.martin@fleetpulse.local', 'EMAIL',   'SENT'),
          ('BB-003-BB', NOW() - INTERVAL '6 hours',     'p.durand@fleetpulse.local', 'EMAIL',   'FAILED'),
          ('BB-005-BB', NOW() - INTERVAL '3 days',      'p.durand@fleetpulse.local', 'EMAIL',   'SENT'),
          ('CC-001-CC', NOW() - INTERVAL '10 days',     'j.martin@fleetpulse.local', 'WEBHOOK', 'SENT'),
          ('CC-003-CC', NOW() - INTERVAL '30 minutes',  'p.durand@fleetpulse.local', 'EMAIL',   'SENT'),
          ('CC-005-CC', NOW() - INTERVAL '2 days',      'p.durand@fleetpulse.local', 'EMAIL',   'SENT')
     ) AS n(alert_vehicle_plate, alert_triggered_at, sent_to, channel, status)
         JOIN vehicle v ON v.license_plate = n.alert_vehicle_plate
         JOIN alert al ON al.vehicle_id = v.id AND al.triggered_at = n.alert_triggered_at
WHERE NOT EXISTS (
    SELECT 1 FROM notification_history nh
    WHERE nh.alert_id = al.id
    AND nh.sent_to = n.sent_to
    AND nh.channel = n.channel
);

-- ---------------------------------
-- TELEMETRY_READINGS — 7 days, one reading every 30 minutes,
-- for all non-decommissioned vehicles. vehicle_id resolved
-- directly from the already-committed vehicle table.
-- ---------------------------------
INSERT INTO telemetry_readings (time, vehicle_id, temperature, vibration, oil_level, rpm, mileage)
SELECT
    ts AS time,
    v.id AS vehicle_id,
    CASE v.vehicle_type
        WHEN 'VAN'   THEN 85 + (random() * 6 - 3)
        WHEN 'TRUCK' THEN 90 + (random() * 8 - 4)
        ELSE               80 + (random() * 4 - 2)
END AS temperature,
    CASE v.vehicle_type
        WHEN 'VAN'   THEN 2.0 + (random() * 1.0 - 0.5)
        WHEN 'TRUCK' THEN 4.5 + (random() * 2.0 - 1.0)
        ELSE               1.2 + (random() * 0.6 - 0.3)
END AS vibration,
    70 + (random() * 20 - 10) AS oil_level,
    CASE v.vehicle_type
        WHEN 'VAN'   THEN 1800 + (random() * 400 - 200)
        WHEN 'TRUCK' THEN 1600 + (random() * 500 - 250)
        ELSE               2200 + (random() * 300 - 150)
END AS rpm,
    40000 + (random() * 60000) AS mileage
FROM vehicle v
CROSS JOIN LATERAL generate_series(
    NOW() - INTERVAL '7 days',
    NOW(),
    INTERVAL '30 minutes'
) AS ts
WHERE v.status != 'DECOMMISSIONED'
AND NOT EXISTS (
    SELECT 1 FROM telemetry_readings tr2
    WHERE tr2.vehicle_id = v.id
    AND tr2.time >= NOW() - INTERVAL '7 days'
);

-- ---------------------------------
-- ANOMALY_SCORES — one score per telemetry reading, elevated near
-- each vehicle's most recent alert.
-- ---------------------------------
INSERT INTO anomaly_scores (time, vehicle_id, score, model_version)
SELECT
    tr.time,
    tr.vehicle_id,
    LEAST(1.0, GREATEST(0.0,
                        CASE
                            WHEN latest_alert.triggered_at IS NOT NULL
                                AND tr.time BETWEEN latest_alert.triggered_at - INTERVAL '2 hours'
                            AND latest_alert.triggered_at + INTERVAL '2 hours'
                            THEN 0.55 + (random() * 0.35)
                            ELSE 0.05 + (random() * 0.30)
                            END
               )) AS score,
    'v1' AS model_version
FROM telemetry_readings tr
         LEFT JOIN LATERAL (
    SELECT triggered_at
    FROM alert a
    WHERE a.vehicle_id = tr.vehicle_id
    ORDER BY triggered_at DESC
        LIMIT 1
) latest_alert ON true
WHERE NOT EXISTS (
    SELECT 1 FROM anomaly_scores as2
    WHERE as2.vehicle_id = tr.vehicle_id
    AND as2.time >= NOW() - INTERVAL '7 days'
);